# config.yaml

dataset:
  lang_pair: ["en", "am"]
  selected_sources: ["github"] 

  hf:
    - name: "smol"
      path: "google/smol"
      split: "train"
      config_name: "smolsent__en_am"
      src_col: "src"
      tgt_col: "trg"

  github:
    - name: "parallel-corpus"
      src_url: "https://raw.githubusercontent.com/AAUThematic4LT/Parallel-Corpora-for-Ethiopian-Languages/refs/heads/master/Exp%20I-English%20to%20Local%20Lang/Legal/amh_eng/p_eng_ea.txt"
      tgt_url: "https://raw.githubusercontent.com/AAUThematic4LT/Parallel-Corpora-for-Ethiopian-Languages/refs/heads/master/Exp%20I-English%20to%20Local%20Lang/Legal/amh_eng/p_amh_ea.txt"

  opus:
    - name: "wikimedia"
      url: "https://object.pouta.csc.fi/OPUS-wikimedia/v20230407/moses/am-en.txt.zip"
      # base_url: "https://object.pouta.csc.fi/OPUS-wikimedia"
      # format: "moses"
      # filename_template: "moses/en-am.txt.zip"
    - name: "TED2020"
      url: "https://object.pouta.csc.fi/OPUS-TED2020/v1/moses/am-en.txt.zip"

download:
  output_dir: "raw/"
  dataset_cache: "dataset_cache"
  model_cache: "model_cache"

preprocessing:
  lowercase: true
  apply_rule_filter: true
  apply_semantic_filter: true

filters:
  rule_filter:
    min_length: 3
    max_length: 200
    max_length_ratio: 2.0
  semantic_filter:
    threshold: 0.7
    chunk_size: 1000

validation:
  quality_estimation: true
  language_detection: true

output:
  filtered_prefix: "filtered"
  save_format: "hf"  # or txt, csv, json
  save_dir: "preprocess_outputs"


logging:
  debug: true
  log_dir: "logs/"
  log_file: "en-am.log"