# Arabic (ar) config.yaml

dataset:
  lang_pair: ["en", "ar"]
  selected_sources: ["opus", "hf", "url"]

  hf:

    - name: "multiun"
      path: "Helsinki-NLP/multiun"
      split: "train"
      config_name: "ar-en"
      src_key: "en"
      tgt_key: "ar"
      column: "translation"
      format: "nested_translation"

    - name: "quran_multilingual_parallel"
      path: "freococo/quran_multilingual_parallel"
      split: "train"
      config_name: "en-ar"
      src_col: "source_string"
      tgt_col: "target_string"
      format: "flat_column"

  opus:
    - name: "GNOME"
      url: "https://object.pouta.csc.fi/OPUS-GNOME/v1/moses/ar-en.txt.zip"
    - name: "wikimedia"
      url: "https://object.pouta.csc.fi/OPUS-wikimedia/v20230407/moses/ar-en.txt.zip"
    - name: "TED2020"
      url: "https://object.pouta.csc.fi/OPUS-TED2020/v1/moses/ar-en.txt.zip"
    - name: "bible-uedin"
      url: "https://object.pouta.csc.fi/OPUS-bible-uedin/v1/moses/ar-en.txt.zip"
    - name: "GNOME"
      url: "https://object.pouta.csc.fi/OPUS-GNOME/v1/moses/ar-en.txt.zip"
    - name: "KDE4"
      url: "https://object.pouta.csc.fi/OPUS-KDE4/v2/moses/ar-en.txt.zip"
    - name: "Ubuntu"
      url: "https://object.pouta.csc.fi/OPUS-Ubuntu/v14.10/moses/ar-en.txt.zip"

    #- name: "Tatoeba"
   #   url: "https://object.pouta.csc.fi/OPUS-Tatoeba/v2023-04-12/moses/ar-en.txt.zip"
    - name: "ELRC-wikipedia_health"
      url: "https://object.pouta.csc.fi/OPUS-ELRC-wikipedia_health/v1/moses/ar-en.txt.zip"
    #- name: "MultiUN"
    #  url: "https://object.pouta.csc.fi/OPUS-MultiUN/v1/moses/ar-en.txt.zip"


  url:
    - name: "arabic-english-parallel-corpus"
      url: "https://www.kaggle.com/datasets/mohamedmustafa/arabicenglishparallelcorpus"
      format: "csv"
    - name: "un-arabic-english"
      url: "https://object.pouta.csc.fi/OPUS-UN/v1/moses/ar-en.txt.zip"
      format: "txt"
    - name: "arabic-news-parallel"
      url: "https://github.com/aub-mind/Arabic-NLP/raw/master/data/parallel/ar-en-news.zip"
      format: "txt"

  table:
    - name: "mt-evaluation-arabic"
      url: "https://zenodo.org/records/3734260/files/arabic.tsv?download=1"
      file_type: "tsv"
      min_score: 0.6
      target:
        model: "fasttext"


download:
  output_dir: "raw/"
  dataset_cache: "dataset_cache"
  model_cache: "model_cache"

preprocessing:
  lowercase: true
  apply_rule_filter: true
  apply_semantic_filter: true
  from_cache: true
  max_total_rows: 1500000
  chunk_size_process: 100000

filters:
  rule_filter:
    min_length: 3
    max_length: 200
    max_length_ratio: 2.0
  semantic_filter:
    threshold: 0.6
    chunk_size: 10000
    batch_size: 7680
  lang_detect_filter:
    batch_size: 40960
    target:
      model: "fasttext"
      lang_code: "ar"
      min_score: 0.6
    src:
      model: "fasttext"
      lang_code: "en"
      min_score: 0.6

validation:
  quality_estimation: true
  language_detection: true
  qe_type: "sentence_level"
  qe_threshold: 0.6

output:
  filtered_prefix: "filtered"
  save_format: "hf"  # or txt, csv, json
  save_dir: "preprocess_outputs/"


merge_and_dedup:
  merge: true
  dedup: true
  dedup_against_test: false

logging:
  debug: true
  log_dir: "logs/"
  log_file: "en-ar.log"
