dataset:
  lang_pair: ["en", "ha"]
  selected_sources: ["hf", "url"]
  hf:
    - name: "flores"
      path: "facebook/flores"
      split: "dev"
      config_name: "eng_Latn-hau_Latn"
      src_col: "sentence_eng_Latn"
      tgt_col: "sentence_hau_Latn"
      format: "flat_column"
    - name: "smol"
      path: "google/smol"
      split: "train"
      config_name: "smolsent__en_ha"
      src_col: "src"
      tgt_col: "trg"
      format: "flat_column"
    - name: "mafand"
      path: "masakhane/mafand"
      split: "train"
      column: "translation"
      src_key: "en"
      tgt_key: "hau"
      format: "nested_translation"
    - name: "mafand-dev"
      path: "masakhane/mafand"
      split: "validation"
      column: "translation"
      src_key: "en"
      tgt_key: "hau"
      format: "nested_translation"
    - name: "mafand-test"
      path: "masakhane/mafand"
      split: "test"
      column: "translation"
      src_key: "en"
      tgt_key: "hau"
      format: "nested_translation"
    - name: "Pontoon-Translations"
      path: "ayymen/Pontoon-Translations"
      split: "train"
      config_name: "en-ha"
      src_col: "source_string"
      tgt_col: "target_string"
      format: "flat_column"
    - name: "Weblate-Translations"
      path: "ayymen/Weblate-Translations"
      split: "train"
      config_name: "en-ha"
      src_col: "source_string"
      tgt_col: "target_string"
      format: "flat_column"
    - name: "ntrex"
      path: "davidstap/NTREX"
      split: "test"
      src_config: "eng_Latn"
      tgt_config: "hau_Latn"
      column: "text"
      "format": "dual_config"
    - name: "HausaVG"
      path: "HausaNLP/HausaVG"
      split: "train"
      src_col: "en_text"
      tgt_col: "ha_text"
      format: "flat_column"
    - name: "polynews-parallel"
      path: "aiana94/polynews-parallel"
      split: "train"
      config_name: "eng_Latn-hau_Latn"
      src_col: "src"
      tgt_col: "tgt"
      format: "flat_column"
    - name: "quran_multilingual_parallel"
      path: "freococo/quran_multilingual_parallel"
      split: "train"
      config_name: "default"
      src_col: "english"
      tgt_col: "hausa"
      format: "flat_column"
    - name: "AfriDocMT-tech"
      path: "masakhane/AfriDocMT"
      split: "train"
      config_name: "tech"
      src_col: "en"
      tgt_col: "ha"
      format: "flat_column"
    - name: "AfriDocMT-health"
      path: "masakhane/AfriDocMT"
      split: "train"
      config_name: "health"
      src_col: "en"
      tgt_col: "ha"
      format: "flat_column"
  url:
    - name: "Gamayun-medium-kit"
      src_url: "https://raw.githubusercontent.com/CLEAR-Global/Gamayun-kits/main/data/English-Hausa/gamayun-medium-kit.en"
      tgt_url: "https://raw.githubusercontent.com/CLEAR-Global/Gamayun-kits/main/data/English-Hausa/gamayun-medium-kit.ha"
    - name: "hausa-corpus"
      src_url: "https://raw.githubusercontent.com/HausaNLP/hausa-corpus/master/data/train.en"
      tgt_url: "https://raw.githubusercontent.com/HausaNLP/hausa-corpus/master/data/train.ha"
  table: []

download:
  output_dir: "raw/"
  dataset_cache: "dataset_cache"
  model_cache: "model_cache"

preprocessing:
  lowercase: true
  apply_rule_filter: true
  apply_semantic_filter: true
  apply_lang_detect_filter: false
  from_cache: false

filters:
  rule_filter:
    min_length: 3
    max_length: 200
    max_length_ratio: 2.0
  semantic_filter:
    threshold: 0.7
    chunk_size: 1000
  lang_detect_filter:
    batch_size: 1000
    min_score: 0.5

validation:
  quality_estimation: true
  language_detection: true

output:
  filtered_prefix: "filtered"
  save_format: "hf"
  save_dir: "preprocess_outputs"

logging:
  debug: true
  log_dir: "logs/"
  log_file: "en-ha.log"