dataset:
  lang_pair:
  - en
  - so
  selected_sources:
  - hf
  - opus
  - url
  hf:
   - name: smol
     path: google/smol
     split: train
     config_name: smolsent__en_so
     src_col: src
     tgt_col: trg
     format: flat_column
   - name: nazimali-quran-itani-maududi
     path: nazimali/quran
     split: train
     src_col: translation-en-itani
     tgt_col: translation-so-abduh
     format: flat_column
   - name: ntrex
     path: davidstap/NTREX
     split: test
     src_config: eng_Latn
     tgt_config: som_Latn
     column: text
     format: dual_config
   - name: opus_infopankki
     path: Helsinki-NLP/opus_infopankki
     split: train
     config_name: en-so
     column: translation
     src_key: en
     tgt_key: so
     format: nested_translation
   - name: Weblate-Translations
     path: ayymen/Weblate-Translations
     split: train
     config_name: en-so
     src_col: source_string
     tgt_col: target_string
     format: flat_column
   - name: quran_multilingual_parallel
     path: freococo/quran_multilingual_parallel
     split: train
     config_name: default
     src_col: english
     tgt_col: somali
     format: flat_column
   - name: subscene
     path: refine-ai/subscene
     config_name: somali
     split: train
     src_col: src
     tgt_col: tgt
     format: flat_column
     trust_remote_code: true
   - name: ted_talks_iwslt
     path: IWSLT/ted_talks_iwslt
     split: train
     language_pair: ["en", "so"]
     year: "2014"
     column: translation
     src_key: en
     tgt_key: so
     format: nested_translation

  opus:
  - name: tico-19
    url: https://object.pouta.csc.fi/OPUS-tico-19/v2020-10-28/moses/en-so.txt.zip
  - name: TED2020
    url: https://object.pouta.csc.fi/OPUS-TED2020/v1/moses/en-so.txt.zip
  - name: tanzil
    url: https://object.pouta.csc.fi/OPUS-Tanzil/v1/moses/en-so.txt.zip
  - name: infopankki
    url: https://object.pouta.csc.fi/OPUS-infopankki/v1/moses/en-so.txt.zip
  - name: wikimedia
    url: https://object.pouta.csc.fi/OPUS-wikimedia/v20230407/moses/en-so.txt.zip
  - name: OpenSubtitles
    url: https://object.pouta.csc.fi/OPUS-OpenSubtitles/v2024/moses/en-so.txt.zip
  - name: GNOME
    url: https://object.pouta.csc.fi/OPUS-GNOME/v1/moses/en-so.txt.zip
  - name: Tatoeba
    url: https://object.pouta.csc.fi/OPUS-Tatoeba/v2023-04-12/moses/en-so.txt.zip
  - name: bible-uedin
    url: https://object.pouta.csc.fi/OPUS-bible-uedin/v1/moses/en-so.txt.zip

url:
  - name: horn-mt
    src_url: https://raw.githubusercontent.com/asmelashteka/HornMT/refs/heads/main/data/eng.txt
    tgt_url: https://raw.githubusercontent.com/asmelashteka/HornMT/refs/heads/main/data/som.txt

download:
  output_dir: raw/
  dataset_cache: dataset_cache
  model_cache: model_cache
preprocessing:
   lowercase: true
   apply_rule_filter: true
   apply_semantic_filter: true
   from_cache: true
   apply_flores_leakage_filter: true
filters:
  rule_filter:
    min_length: 3
    max_length: 200
    max_length_ratio: 2.0
  semantic_filter:
    threshold: 0.6
    chunk_size: 1024
  lang_detect_filter:
    source:
      model: "fasttext"
      lang_code: "en"
      batch_size: 1024
      min_score: 0.6
    target:
      model: "afrolid"
      lang_code: "som"
      batch_size: 1024
      min_score: 0.6
  flores_leakage_filter:
    enabled: true
    flores_path: "facebook/flores"
    src_col: "sentence_eng_Latn"
    tgt_col: "sentence_som_Latn"
    split: "devtest"
    use_fuzzy: false
    threshold: 0.6
validation:
  quality_estimation: true
merge:
  enabled: true
  qe_min_score: 0.6
output:
  filtered_prefix: "filtered"
  save_format: "hf"  # or txt, csv, json
  save_dir: "preprocess_outputs/"
logging:
  debug: true
  log_dir: logs/
  log_file: en-so.log
