dataset:
  lang_pair:
  - en
  - sw
  selected_sources:
  - opus
  - hf
  - url
  - table
  hf:
  - name: smol
    path: google/smol
    split: train
    config_name: smolsent__en_sw
    src_col: src
    tgt_col: trg
    format: flat_column
  - name: mafand
    path: masakhane/mafand
    split: train+validation+test
    config_name: en-swa
    src_key: en
    tgt_key: swa
    column: translation
    format: nested_translation
  - name: Pontoon-Translations
    path: ayymen/Pontoon-Translations
    split: train
    config_name: en-sw
    src_col: source_string
    tgt_col: target_string
    format: flat_column
  - name: Weblate-Translations
    path: ayymen/Weblate-Translations
    split: train
    config_name: en-sw
    src_col: source_string
    tgt_col: target_string
    format: flat_column
  - name: quran
    path: nazimali/quran
    split: train
    src_col: translation-en-itani
    tgt_col: translation-sw-barwani
    format: flat_column
  - name: ted_talks_iwslt
    path: IWSLT/ted_talks_iwslt
    split: train
    column: translation
    src_key: en
    tgt_key: sw
    format: nested_translation
  - name: ntrex
    path: davidstap/NTREX
    split: test
    src_config: eng_Latn
    tgt_config: swa_Latn
    column: text
    format: dual_config
  - name: English-Swahili-Sentence-Pairs
    path: Rogendo/English-Swahili-Sentence-Pairs
    split: train
    src_col: English sentence
    tgt_col: Swahili Translation
    format: flat_column
  - name: subscene
    path: refine-ai/subscene
    split: train
    config_name: swahili
    src_col: src
    tgt_col: tgt
    format: flat_column
    trust_remote_code: true
  - name: polynews-parallel
    path: aiana94/polynews-parallel
    split: train
    config_name: eng_Latn-swh_Latn
    src_col: src
    tgt_col: tgt
    format: flat_column
  - name: AfriDocMT-tech
    path: masakhane/AfriDocMT
    split: train
    config_name: tech
    src_col: en
    tgt_col: sw
    format: flat_column
  - name: AfriDocMT-health
    path: masakhane/AfriDocMT
    split: train
    config_name: health
    src_col: en
    tgt_col: sw
    format: flat_column
  - name: kenyan-low-resource-language-data
    path: thinkKenya/kenyan-low-resource-language-data
    split: train
    config_name: dav_swa
    column: translation
    src_key: swa
    tgt_key: dav
    format: nested_translation
    trust_remote_code: true
    auth_token: hf_SJlKoabMmsVgVOMIXquRDYhadtYRYmAxAKct 
  opus:
  - name: tanzil
    url: https://object.pouta.csc.fi/OPUS-Tanzil/v1/moses/en-sw.txt.zip
  - name: tico-19
    url: https://object.pouta.csc.fi/OPUS-tico-19/v2020-10-28/moses/en-sw.txt.zip
  - name: TED2020
    url: https://object.pouta.csc.fi/OPUS-TED2020/v1/moses/en-sw.txt.zip
  - name: wikimedia
    url: https://object.pouta.csc.fi/OPUS-wikimedia/v20230407/moses/en-sw.txt.zip
  - name: ELRC-wikipedia_health
    url: https://object.pouta.csc.fi/OPUS-ELRC-wikipedia_health/v1/moses/en-sw.txt.zip
  - name: ELRC-3073-wikipedia_health
    url: https://object.pouta.csc.fi/OPUS-ELRC-3073-wikipedia_health/v1/moses/en-sw.txt.zip
  - name: ELRC_2922
    url: https://object.pouta.csc.fi/OPUS-ELRC_2922/v1/moses/en-sw.txt.zip
  - name: OpenSubtitles
    url: https://object.pouta.csc.fi/OPUS-OpenSubtitles/v2024/moses/en-sw.txt.zip
  - name: GlobalVoices
    url: https://object.pouta.csc.fi/OPUS-GlobalVoices/v2018q4/moses/en-sw.txt.zip
  - name: GNOME
    url: https://object.pouta.csc.fi/OPUS-GNOME/v1/moses/en-sw.txt.zip
  - name: EUbookshop
    url: https://object.pouta.csc.fi/OPUS-EUbookshop/v2/moses/en-sw.txt.zip
download:
  output_dir: raw/
  dataset_cache: dataset_cache
  model_cache: model_cache
models:
  fasttext: lid.176.bin
preprocessing:
  lowercase: true
  apply_rule_filter: true
  apply_semantic_filter: true
  from_cache: false
filters:
  rule_filter:
    min_length: 3
    max_length: 200
    max_length_ratio: 2.0
  semantic_filter:
    threshold: 0.7
    chunk_size: 1000
  lang_detect_filter:
    batch_size: 1000
    min_score: 0.4
validation:
  quality_estimation: true
  language_detection: true
output:
  filtered_prefix: filtered
  save_format: hf
  save_dir: preprocess_outputs
logging:
 debug: true
 log_dir: logs/
 log_file: en-sw.log
