# config.yaml

dataset:
  lang_pair: ["en", "sw"]
  selected_sources: ["hf", "opus"] 

  hf:
    - name: "smol"
      path: "google/smol"
      split: "train"
      config_name: "smolsent__en_sw"
      src_col: "src"
      tgt_col: "trg"
      format: "flat_column"
    - name: "mafand"
      path: "masakhane/mafand"
      split: "train+validation+test"
      config_name: "en-swa"
      src_key: "en"
      tgt_key: "swa"
      column: "translation"
      "format": "nested_translation"
    - name: "Pontoon-Translations"
      path: "ayymen/Pontoon-Translations"
      split: "train"
      config_name: "en-sw"
      src_col: "source_string"
      tgt_col: "target_string"
      format: "flat_column"
    - name: "Weblate-Translations"
      path: "ayymen/Weblate-Translations"
      split: "train"
      config_name: "en-sw"
      src_col: "source_string"
      tgt_col: "target_string"
      format: "flat_column"
    - name: "nazimali-quran-itani-maududi"
      path: "nazimali/quran"
      split: "train"
      src_col: "translation-en-itani"
      tgt_col: "translation-sw-barwani"
      format: "flat_column"
    - name: "ntrex"
      path: "davidstap/NTREX"
      split: "test"
      src_config: "eng_Latn"
      tgt_config: "swa_Latn"
      column: "text"
      format: "dual_config"
    - name: "ted_talks_iwslt-2014"
      path: "IWSLT/ted_talks_iwslt"
      split: "train"
      src_key: "en"
      tgt_key: "sw"
      column: "translation"
      format: "nested_translation"
      extra_args:
        trust_remote_code: True
        language_pair: ["en", "sw"]
        year: "2014"
    - name: "ted_talks_iwslt-2015"
      path: "IWSLT/ted_talks_iwslt"
      split: "train"
      src_key: "en"
      tgt_key: "sw"
      column: "translation"
      format: "nested_translation"
      extra_args:
        trust_remote_code: True
        language_pair: ["en", "sw"]
        year: "2015"
    - name: "wmt24pp"
      path: "google/wmt24pp"
      split: "train"
      config_name: "en-sw_KE"
      src_col: "source"
      tgt_col: "target"
      format: "flat_column"
    - name: "sunbird-salt"
      path: "Sunbird/salt"
      split: "train+dev+test"
      config_name: "text-all"
      src_col: "eng_source_text"
      tgt_col: "swa_text"
      format: "flat_column"


    

    #AfriDocMT dataset subsets
    - name: "AfriDocMT-tech"
      path: "masakhane/AfriDocMT"
      split: "train"
      config_name: "tech"
      src_col: "en"
      tgt_col: "sw"
      format: "flat_column"
    - name: "AfriDocMT-health"
      path: "masakhane/AfriDocMT"
      split: "train"
      config_name: "health"
      src_col: "en"
      tgt_col: "sw"
      format: "flat_column"
    - name: "AfriDocMT-doc_tech"
      path: "masakhane/AfriDocMT"
      split: "train"
      config_name: "doc_tech"
      src_col: "en"
      tgt_col: "sw"
      format: "flat_column"
    - name: "AfriDocMT-doc_health"
      path: "masakhane/AfriDocMT"
      split: "train"
      config_name: "doc_health"
      src_col: "en"
      tgt_col: "sw"
      format: "flat_column"
    - name: "AfriDocMT-doc_tech_25"
      path: "masakhane/AfriDocMT"
      split: "train"
      config_name: "doc_tech_25"
      src_col: "en"
      tgt_col: "sw"
      format: "flat_column"
    - name: "AfriDocMT-doc_health_25"
      path: "masakhane/AfriDocMT"
      split: "train"
      config_name: "doc_health_25"
      src_col: "en"
      tgt_col: "sw"
      format: "flat_column"
    - name: "AfriDocMT-doc_tech_5"
      path: "masakhane/AfriDocMT"
      split: "train"
      config_name: "doc_tech_5"
      src_col: "en"
      tgt_col: "sw"
      format: "flat_column"
    - name: "AfriDocMT-doc_health_5"
      path: "masakhane/AfriDocMT"
      split: "train"
      config_name: "doc_health_5"
      src_col: "en"
      tgt_col: "sw"
      format: "flat_column"
    - name: "AfriDocMT-doc_tech_10"
      path: "masakhane/AfriDocMT"
      split: "train"
      config_name: "doc_tech_10"
      src_col: "en"
      tgt_col: "sw"
      format: "flat_column"
    - name: "AfriDocMT-doc_health_10"
      path: "masakhane/AfriDocMT"
      split: "train"
      config_name: "doc_health_10"
      src_col: "en"
      tgt_col: "sw"
      format: "flat_column"


  opus:
    - name: "wikimedia"
      url: "https://object.pouta.csc.fi/OPUS-wikimedia/v20230407/moses/en-sw.txt.zip"
    - name: "TED2020"
      url: "https://object.pouta.csc.fi/OPUS-TED2020/v1/moses/en-sw.txt.zip"
    - name: "GlobalVoices"
      url: "https://object.pouta.csc.fi/OPUS-GlobalVoices/v2018q4/moses/en-sw.txt.zip"
    - name: "GNOME"
      url: "https://object.pouta.csc.fi/OPUS-GNOME/v1/moses/en-sw.txt.zip"
    - name: "OpenSubtitles"
      url: "https://object.pouta.csc.fi/OPUS-OpenSubtitles/v2024/moses/en-sw.txt.zip"
    - name: "Tanzil"
      url: "https://object.pouta.csc.fi/OPUS-Tanzil/v1/moses/en-sw.txt.zip"
    - name: "ELRC_2922"
      url: "https://object.pouta.csc.fi/OPUS-ELRC_2922/v1/moses/en-sw.txt.zip"
    - name: "ELRC-3073-wikipedia_health"
      url: "https://object.pouta.csc.fi/OPUS-ELRC-3073-wikipedia_health/v1/moses/en-sw.txt.zip"
    - name: "ELRC-wikipedia_health"
      url: "https://object.pouta.csc.fi/OPUS-ELRC-wikipedia_health/v1/moses/en-sw.txt.zip"
    - name: "tico-19"
      url: "https://object.pouta.csc.fi/OPUS-tico-19/v2020-10-28/moses/en-sw.txt.zip"
    - name: "EUbookshop"
      url: "https://object.pouta.csc.fi/OPUS-EUbookshop/v2/moses/en-sw.txt.zip"

     

  # url:



  # table:




download:
  output_dir: "raw/"
  dataset_cache: "dataset_cache"
  model_cache: "model_cache"

preprocessing:
  lowercase: true
  apply_rule_filter: true
  apply_semantic_filter: true
  from_cache: true

filters:
  rule_filter:
    min_length: 3
    max_length: 200
    max_length_ratio: 2.0
  semantic_filter:
    threshold: 0.7
    chunk_size: 1000
  lang_detect_filter:
    batch_size: 1000
    min_score: 0.9

validation:
  quality_estimation: true
  language_detection: true

output:
  filtered_prefix: "filtered"
  save_format: "hf"  # or txt, csv, json
  save_dir: "preprocess_outputs"


logging:
  debug: true
  log_dir: "logs/"
  log_file: "en-sw.log"