dataset:
  lang_pair:
  - en
  - yo
  selected_sources:
  - opus
  - hf

  opus:
    #- name: QED
    #  url: https://object.pouta.csc.fi/OPUS-QED/v2.0a/moses/en-yor.txt.zip
    # Wikimedia translations - Community-contributed translations
    - name: wikimedia
      url: https://object.pouta.csc.fi/OPUS-wikimedia/v20230407/moses/en-yo.txt.zip
    # Tatoeba - Crowd-sourced example sentences
    - name: Tatoeba
      url: https://object.pouta.csc.fi/OPUS-Tatoeba/v2023-04-12/moses/en-yo.txt.zip
    # GNOME Desktop UI translations
    - name: GNOME
      url: https://object.pouta.csc.fi/OPUS-GNOME/v1/moses/en-yo.txt.zip
    # Ubuntu Software translations
    - name: Ubuntu
      url: https://object.pouta.csc.fi/OPUS-Ubuntu/v14.10/moses/en-yo.txt.zip
    - name: GlobalVoices
      url: https://object.pouta.csc.fi/OPUS-GlobalVoices/v2018q4/moses/en-yo.txt.zip

  hf:
  # --- General & Large-Scale Datasets ---
  - name: opus-100
    path: Helsinki-NLP/opus-100
    split: train
    config_name: en-yo
    column: translation
    src_key: en
    tgt_key: yo
    format: nested_translation
  - name: opus-100-dev
    path: Helsinki-NLP/opus-100
    split: train
    config_name: en-yo
    column: translation
    src_key: en
    tgt_key: yo
    format: nested_translation
  - name: opus-100-test
    path: Helsinki-NLP/opus-100
    split: train
    config_name: en-yo
    column: translation
    src_key: en
    tgt_key: yo
    format: nested_translation
  - name: smol
    path: google/smol
    split: train
    config_name: smolsent__en_yo
    src_col: src
    tgt_col: trg
    format: flat_column

  # - name: tatoeba-hf
  #   path: Helsinki-NLP/tatoeba
  #   split: train
  #   config_name: en-yo
  #   column: translation
  #   src_key: en
  #   tgt_key: yo
  #   format: nested_translation
  #   trust_remote_code: true

  # --- African Language Specific Datasets ---
  - name: mafand
    path: masakhane/mafand
    split: train
    config_name: en-yor
    column: translation
    src_key: en
    tgt_key: yor
    format: nested_translation
  - name: mafand-dev
    path: masakhane/mafand
    split: train
    config_name: en-yor
    column: translation
    src_key: en
    tgt_key: yor
    format: nested_translation
  - name: mafand-test
    path: masakhane/mafand
    split: train
    config_name: en-yor
    column: translation
    src_key: en
    tgt_key: yor
    format: nested_translation

  - name: AfriDocMT-health
    path: masakhane/AfriDocMT
    split: train
    config_name: health
    src_col: en
    tgt_col: yo
    format: flat_column

  # MENYO-20k: Multi-domain English-Yoruba corpus
  - name: menyo20k_mt-train
    path: UdS-LSV/menyo20k_mt
    split: train
    column: translation
    src_key: en
    tgt_key: yo
    format: nested_translation
    trust_remote_code: true
  - name: menyo20k_mt-dev
    path: UdS-LSV/menyo20k_mt
    split: validation
    column: translation
    src_key: en
    tgt_key: yo
    format: nested_translation
    trust_remote_code: true
  - name: menyo20k_mt-test
    path: UdS-LSV/menyo20k_mt
    split: test
    column: translation
    src_key: en
    tgt_key: yo
    format: nested_translation
    trust_remote_code: true

  - name: ntrex
    path: davidstap/NTREX
    split: test
    src_config: eng_Latn
    tgt_config: yor_Latn
    column: text
    format: dual_config
    
  # --- Other Multilingual Sources ---
  - name: Pontoon-Translations
    path: ayymen/Pontoon-Translations
    split: train
    config_name: en-yo
    src_col: source_string
    tgt_col: target_string
    format: flat_column
  - name: Weblate-Translations
    path: ayymen/Weblate-Translations
    split: train
    config_name: en-yo
    src_col: source_string
    tgt_col: target_string
    format: flat_column
  - name: quran_multilingual_parallel
    path: freococo/quran_multilingual_parallel
    split: train
    config_name: default
    src_col: english
    tgt_col: yoruba
    format: flat_column

  # Yoruba Audio Translation Dataset - ASR with translations
  - name: yoruba_audio_translated-train
    path: amanuelbyte/yoruba_audio_translated
    split: train
    src_col: English Sentence
    tgt_col: text
    format: flat_column



download:
  output_dir: raw/
  dataset_cache: dataset_cache
  model_cache: model_cache
preprocessing:
   lowercase: true
   apply_rule_filter: true
   apply_semantic_filter: true
   apply_lang_detect_filter: true
   apply_quality_estimation_filter: true
   from_cache: true
   apply_flores_leakage_filter: true
filters:
  rule_filter:
    min_length: 3
    max_length: 200
    max_length_ratio: 2.0
  semantic_filter:
    threshold: 0.6
    chunk_size: 10000
    batch_size: 7680
  lang_detect_filter:
    src:
      model: "fasttext"
      lang_code: "en"
      batch_size: 7680
      min_score: 0.6
    target:
      model: "afrolid"
      lang_code: "yor"
      batch_size: 7680
      min_score: 0.6
  flores_leakage_filter:
    enabled: true
    flores_path: "facebook/flores"
    src_col: "sentence_eng_Latn"
    tgt_col: "sentence_yor_Latn"
    split: "devtest"
    use_fuzzy: false
    threshold: 0.6
validation:
  quality_estimation: true
  language_detection: true
  qe_type: "sentence_level"
  qe_threshold: 0.6

quality_estimation:
  # Model configuration
  model_name: "masakhane/africomet-qe-stl-1.1"
  src_lang: "en"
  tgt_lang: "yo"

  # Filtering configuration
  apply_filter: true  # Set to false to pass all pairs through
  threshold: 0.6
  sentence_level: true  # true for sentence-level, false for document-level

  # Batch processing
  batch_size: 32

  # Model type selection
  model_type: "comet"  # Options: "comet", "custom", "huggingface"

merge_and_dedup:
  merge: true
  dedup: true
  dedup_against_test: false
  
output:
  filtered_prefix: "filtered"
  save_format: "hf"  # or txt, csv, json
  save_dir: "preprocess_outputs/"
logging:
  debug: true
  log_dir: logs/
  log_file: en-yo.log
