dataset:
  lang_pair:
  - en
  - zu
  selected_sources:
  - hf
  - opus
  - url
  - table
  hf:
  - name: smol
    path: google/smol
    split: train
    config_name: smolsent__en_zu
    src_col: src
    tgt_col: trg
    format: flat_column
  - name: Pontoon-Translations
    path: ayymen/Pontoon-Translations
    split: train
    config_name: en-zu
    src_col: source_string
    tgt_col: target_string
    format: flat_column
  - name: Weblate-Translations
    path: ayymen/Weblate-Translations
    split: train
    config_name: en-zu
    src_col: source_string
    tgt_col: target_string
    format: flat_column
  - name: ntrex
    path: davidstap/NTREX
    split: test
    src_config: eng_Latn
    tgt_config: zul_Latn
    column: text
    format: dual_config
  - name: polynews-parallel
    path: aiana94/polynews-parallel
    split: train
    config_name: eng_Latn-zul_Latn
    src_col: src
    tgt_col: tgt
    format: flat_column
  - name: mafand
    path: masakhane/mafand
    split: train
    config_name: en-zul
    column: translation
    src_key: en
    tgt_key: zul
    format: nested_translation
  - name: mafand-dev
    path: masakhane/mafand
    split: validation
    config_name: en-zul
    column: translation
    src_key: en
    tgt_key: zul
    format: nested_translation
  - name: mafand-test
    path: masakhane/mafand
    split: test
    config_name: en-zul
    column: translation
    src_key: en
    tgt_key: zul
    format: nested_translation
  - name: AfriDocMT-health
    path: masakhane/AfriDocMT
    split: train
    config_name: health
    src_col: en
    tgt_col: zu
    format: flat_column
  opus:
  #- name: QED
  #  url: https://object.pouta.csc.fi/OPUS-QED/v2.0a/moses/en-zul.txt.zip
  - name: tico-19
    url: https://object.pouta.csc.fi/OPUS-tico-19/v2020-10-28/moses/en-zu.txt.zip
  - name: GNOME
    url: https://object.pouta.csc.fi/OPUS-GNOME/v1/moses/en-zu.txt.zip
  - name: Tatoeba
    url: https://object.pouta.csc.fi/OPUS-Tatoeba/v2023-04-12/moses/en-zu.txt.zip
  - name: Bible-uedin
    url: https://object.pouta.csc.fi/OPUS-bible-uedin/v1/moses/en-zu.txt.zip
  - name: wikimedia
    url: https://object.pouta.csc.fi/OPUS-wikimedia/v20230407/moses/en-zu.txt.zip
  url:
  - name: ukuxhumana
    src_url: https://raw.githubusercontent.com/LauraMartinus/ukuxhumana/refs/heads/master/clean/en_zu/enzu_parallel.en
    tgt_url: https://raw.githubusercontent.com/LauraMartinus/ukuxhumana/refs/heads/master/clean/en_zu/enzu_parallel.zu
  table:
  - name: zenodo-training
    url: https://zenodo.org/records/5035171/files/en-zu.training.csv?download=1
    file_type: csv
    src_col: en
    tgt_col: zu
  - name: zenodo-eval
    url: https://zenodo.org/records/5035171/files/en-zu.eval.csv?download=1
    file_type: csv
    src_col: en
    tgt_col: zu

download:
  output_dir: raw/
  dataset_cache: dataset_cache
  model_cache: model_cache
preprocessing:
   lowercase: true
   apply_rule_filter: true
   apply_semantic_filter: true
   from_cache: true
   apply_flores_leakage_filter: true
filters:
  rule_filter:
    min_length: 3
    max_length: 200
    max_length_ratio: 2.0
  semantic_filter:
    threshold: 0.6
    chunk_size: 1024
  lang_detect_filter:
    source:
      model: "fasttext"
      lang_code: "en"
      batch_size: 1024
      min_score: 0.6
    target:
      model: "afrolid"
      lang_code: "zul"
      batch_size: 1024
      min_score: 0.6
  flores_leakage_filter:
    enabled: true
    flores_path: "facebook/flores"
    src_col: "sentence_eng_Latn"
    tgt_col: "sentence_zul_Latn"
    split: "devtest"
    use_fuzzy: false
    threshold: 0.6
validation:
  quality_estimation: true
merge:
  enabled: true
  qe_min_score: 0.6
output:
  filtered_prefix: "filtered"
  save_format: "hf"  # or txt, csv, json
  save_dir: "preprocess_outputs/"
logging:
  debug: true
  log_dir: logs/
  log_file: en-zu.log
